import { typeRows, stageRows, PER_M2_ROWS, COST_DRIVERS, SOURCES, COSTS_VERIFIED, estimate } from './costs'

const fmtM = n => `₦${Math.round(n / 1e5) / 10}m`
const range = (k, f = 'standard') => { const [a, b] = estimate(k, f); return `${fmtM(a)}–${fmtM(b)}` }

const COST_CTA = {
    title: 'Get a BOQ-based estimate for your plot',
    text: 'Send us your drawings or a rough brief. We price every bag of cement and length of rebar in an open-book bill of quantities.',
    label: 'Get a BOQ estimate',
    href: '/build-from-abroad#book',
    secondary: { label: 'Get the free 2026 cost guide (PDF)', href: '/cost-guide' },
}

const RELATED_COST = [
    { label: 'Cost of building a house in Nigeria', href: '/guides/cost-of-building-a-house-in-nigeria', text: 'Per-m² rates, every house type and what drives the price.' },
    { label: 'Cost of building a duplex', href: '/guides/cost-of-building-a-duplex-in-nigeria', text: '4- and 5-bedroom duplex costs, stage by stage.' },
    { label: 'Cost of building a bungalow', href: '/guides/cost-of-building-a-bungalow-in-nigeria', text: '2-, 3- and 4-bedroom bungalow costs.' },
    { label: 'How much is a house in Nigeria?', href: '/guides/how-much-is-a-house-in-nigeria', text: 'Buying vs building, in naira, pounds and dollars.' },
    { label: 'Building material prices', href: '/news/material-prices', text: 'Cement, rebar, granite and sand prices, updated as they change.' },
    { label: 'How we build', href: '/how-we-build', text: 'Stage payments, inspections and the documents you get.' },
]
const related = (...skip) => RELATED_COST.filter(r => !skip.includes(r.href))

export const costHub = {
    kind: 'guide',
    path: '/guides/cost-of-building-a-house-in-nigeria',
    title: 'Cost of Building a House in Nigeria (2026) | Artemis Atelier',
    description: `Building a house in Lagos costs about ₦150,000–₦450,000 per m² in 2026. See costs for bungalows and duplexes in naira, pounds and dollars, stage by stage.`,
    breadcrumbs: [{ name: 'Guides', path: '/guides' }, { name: 'Cost of building a house in Nigeria', path: '/guides/cost-of-building-a-house-in-nigeria' }],
    eyebrow: 'Cost guide · 2026',
    h1: 'How much does it cost to build a house in Nigeria in 2026?',
    intro: `In Lagos in 2026, building a house costs roughly **₦150,000 to ₦450,000 per square metre**, excluding land. That puts a 3-bedroom bungalow at about **${range('bungalow-3')}** and a 4-bedroom duplex at about **${range('duplex-4')}** with standard finishes.`,
    updated: COSTS_VERIFIED,
    published: '2026-10-02',
    hero: '/31.jpg',
    heroAlt: 'Design visual of a residential development by Artemis Atelier',
    currency: true,
    whatsappText: 'Hi Artemis, I read your cost guide and would like an estimate for my build.',
    summary: [
        `Basic finish: ₦150,000–₦220,000 per m². Standard: ₦220,000–₦330,000. Premium: ₦330,000–₦450,000+.`,
        `3-bedroom bungalow (~130 m²): ${range('bungalow-3', 'basic')} basic, ${range('bungalow-3')} standard.`,
        `4-bedroom duplex (~280 m²): ${range('duplex-4', 'basic')} basic, ${range('duplex-4')} standard.`,
        'Add land, approvals, external works (fence, gate, borehole, paving) and furniture on top: external works alone usually add 10–20%.',
    ],
    blocks: [
        { t: 'h2', text: 'Cost per square metre' },
        { t: 'p', text: 'The fastest way to estimate a build is gross floor area × a rate for the finish you want. These rates cover everything from foundation to handover for a house on normal soil in Lagos.' },
        { t: 'table', caption: 'Building cost per square metre in Lagos, 2026', head: ['Finish level', 'Cost', 'What it typically includes'], rows: PER_M2_ROWS, note: 'Building only. Excludes land, approvals, external works, furniture and VAT where it applies.' },
        { t: 'h2', text: 'Cost by house type' },
        { t: 'p', text: 'Typical Lagos floor areas multiplied by the rates above. Your design, soil and finishes move these numbers — use them to set a budget, not to sign a contract.' },
        { t: 'table', caption: 'Building cost by house type, 2026', head: ['House type', 'Basic', 'Standard', 'Premium'], rows: typeRows(['bungalow-2', 'bungalow-3', 'bungalow-4', 'duplex-4', 'duplex-5']), note: 'Rounded to the nearest ₦0.5m. Switch currency at the top of the page to see pounds or dollars.' },
        { t: 'cards', items: [
            { h: 'Duplex costs in detail', p: '4- and 5-bedroom duplexes, stage by stage, with ways to save.', href: '/guides/cost-of-building-a-duplex-in-nigeria', cta: 'Duplex guide' },
            { h: 'Bungalow costs in detail', p: '2-, 3- and 4-bedroom bungalows and when a bungalow is the better buy.', href: '/guides/cost-of-building-a-bungalow-in-nigeria', cta: 'Bungalow guide' },
        ] },
        { t: 'h2', text: 'Where the money goes, stage by stage' },
        { t: 'p', text: 'This is also how we split payments: you pay for one stage at a time, and our inspection team signs it off before the next payment is due. Example: 4-bedroom duplex, standard finish.' },
        { t: 'table', caption: 'Building cost by stage, 4-bedroom duplex', head: ['Stage', 'Share', 'Approx. cost', 'What it covers'], rows: stageRows('duplex-4') },
        { t: 'h2', text: 'Current building material prices' },
        { t: 'p', text: 'Materials are about half of a building budget, and their prices move with the exchange rate. These are the latest prices on our tracker.' },
        { t: 'prices', compact: true },
        { t: 'h2', text: 'What makes a build cost more' },
        { t: 'ul', items: COST_DRIVERS },
        { t: 'h2', text: 'What is not in these figures' },
        { t: 'checklist', items: [
            '**Land.** From about ₦15m a plot in Ikorodu to over ₦1bn in Ikoyi. See [buying land in Nigeria from abroad](/guides/buying-land-in-nigeria-from-abroad).',
            '**Approvals.** Lagos building permit (LASPPPA) and other fees depend on size and location; we include them in your project budget once the design is fixed.',
            '**External works.** Fence and gate, paving, borehole, septic tank or soakaway, generator house: usually 10–20% on top.',
            '**Furniture, appliances and solar/inverter systems.**',
            '**A contingency of 5–10%** for price movements and choices made during the build.',
        ] },
        { t: 'h2', text: 'How to get an accurate figure' },
        { t: 'steps', items: [
            { h: 'Soil test and survey', p: 'Tells us what foundation the land needs: the biggest unknown in any estimate.' },
            { h: 'Drawings', p: 'Architectural and structural drawings fix the floor area, spans and quantities.' },
            { h: 'Bill of quantities (BOQ)', p: 'Every item priced: bags of cement, tonnes of rebar, number of blocks, square metres of tiles. Ours are open-book, so you can check each line.' },
            { h: 'Stage budget', p: 'The BOQ is split into stages that match the payment schedule and the inspections. See [how we build](/how-we-build).' },
        ] },
        { t: 'callout', title: 'Building from abroad?', text: 'Diaspora clients often budget in pounds or dollars and pay in naira. We quote in naira, show the currency equivalent on the day, and only ask for each stage payment when the previous stage has been inspected. [How building from abroad works](/build-from-abroad).' },
    ],
    faqs: [
        { q: 'How much does it cost to build a house in Nigeria in 2026?', a: `Roughly ₦150,000–₦450,000 per square metre in Lagos, excluding land. A 3-bedroom bungalow is about ${range('bungalow-3', 'basic')} with basic finishes and ${range('bungalow-3')} with standard finishes; a 4-bedroom duplex is about ${range('duplex-4')} standard.` },
        { q: 'What is the cost per square metre to build a house in Nigeria?', a: 'About ₦150,000–₦220,000 per m² for a basic finish, ₦220,000–₦330,000 for a standard finish and ₦330,000–₦450,000 or more for premium finishes, in Lagos in 2026.' },
        { q: 'How much is that in pounds or dollars?', a: 'Use the currency switch at the top of this page: it converts every figure at the current official rate. At ₦1,767 to £1, a ₦75m duplex is about £42,000.' },
        { q: 'Is it cheaper to build or buy a house in Lagos?', a: 'Building is usually cheaper per square metre and you control quality, but it takes 12–24 months and needs land. Buying is faster but you pay the developer’s margin and can’t see what is inside the walls. See [how much a house costs in Nigeria](/guides/how-much-is-a-house-in-nigeria).' },
        { q: 'How long does it take to build a house in Nigeria?', a: 'A bungalow typically takes 6–12 months and a duplex 12–24 months from approval to handover, depending on funding, design and finishes. Steady stage payments keep a project on schedule.' },
        { q: 'Why do estimates for the same house differ so much?', a: 'Different finish levels, soil conditions and what is included (external works, approvals, VAT). Always compare estimates as itemised BOQs, not single figures.' },
    ],
    sources: SOURCES,
    related: related('/guides/cost-of-building-a-house-in-nigeria'),
    cta: COST_CTA,
}

export const duplexGuide = {
    kind: 'guide',
    path: '/guides/cost-of-building-a-duplex-in-nigeria',
    title: 'Cost of Building a Duplex in Nigeria (2026) | Artemis',
    description: `A 4-bedroom duplex in Lagos costs about ${fmtM(estimate('duplex-4', 'basic')[0])} to ${fmtM(estimate('duplex-4', 'premium')[1])} to build in 2026, excluding land. Stage-by-stage costs in ₦, £ and $.`,
    breadcrumbs: [{ name: 'Guides', path: '/guides' }, { name: 'Cost of building a duplex', path: '/guides/cost-of-building-a-duplex-in-nigeria' }],
    eyebrow: 'Cost guide · Duplex · 2026',
    h1: 'Cost of building a duplex in Nigeria (2026)',
    intro: `Building a **4-bedroom duplex** in Lagos costs about **${range('duplex-4')}** with standard finishes in 2026, and a **5-bedroom duplex** about **${range('duplex-5')}**, excluding land. Basic finishes bring that down by around a third; premium finishes add about a third.`,
    updated: COSTS_VERIFIED,
    published: '2026-10-02',
    hero: '/33.jpg',
    heroAlt: 'Design visual of a duplex development',
    currency: true,
    whatsappText: 'Hi Artemis, I read your duplex cost guide and would like an estimate.',
    summary: [
        `4-bedroom duplex (~280 m²): ${range('duplex-4', 'basic')} basic · ${range('duplex-4')} standard · ${range('duplex-4', 'premium')} premium.`,
        `5-bedroom duplex (~350 m²): ${range('duplex-5', 'basic')} basic · ${range('duplex-5')} standard · ${range('duplex-5', 'premium')} premium.`,
        'Finishing is the biggest single stage (30–40%); the first-floor slab makes a duplex’s frame stage dearer than a bungalow’s.',
        'Timeline: usually 12–24 months from approval to handover.',
    ],
    blocks: [
        { t: 'h2', text: 'Duplex costs at a glance' },
        { t: 'table', caption: 'Duplex building cost, Lagos 2026', head: ['Duplex', 'Basic', 'Standard', 'Premium'], rows: typeRows(['duplex-4', 'duplex-5']), note: 'Building only, excluding land, approvals and external works. Rounded to ₦0.5m.' },
        { t: 'h2', text: '4-bedroom duplex: cost stage by stage' },
        { t: 'table', caption: '4-bedroom duplex cost by stage (standard finish)', head: ['Stage', 'Share', 'Approx. cost', 'What it covers'], rows: stageRows('duplex-4') },
        { t: 'h2', text: '5-bedroom duplex: cost stage by stage' },
        { t: 'table', caption: '5-bedroom duplex cost by stage (standard finish)', head: ['Stage', 'Share', 'Approx. cost', 'What it covers'], rows: stageRows('duplex-5') },
        { t: 'h2', text: 'Why a duplex costs more per m² than a bungalow' },
        { t: 'ul', items: [
            '**The first-floor slab and staircase.** Concrete, rebar and formwork for the suspended floor add a whole extra structural stage.',
            '**Heavier foundations and columns** to carry two floors.',
            '**Scaffolding and working at height** for the upper floor and roof.',
            '**But** a duplex uses less land and roof per bedroom, so on expensive plots it is often the better use of money.',
        ] },
        { t: 'h2', text: 'Ways to save without cutting corners' },
        { t: 'ul', items: [
            'Keep the plan simple: a rectangular footprint and stacked walls and wet rooms cut concrete, rebar and plumbing.',
            'Fix the design before you start. Changes during the build are the most expensive changes.',
            'Buy materials in bulk per stage when prices dip — we track them on our [price tracker](/news/material-prices).',
            'Spend on structure and waterproofing; upgrade finishes later if you need to.',
            'Pay per inspected stage, so you never pay for work that has to be redone.',
        ] },
        { t: 'h2', text: 'Current material prices' },
        { t: 'prices', compact: true },
    ],
    faqs: [
        { q: 'How much does it cost to build a 4-bedroom duplex in Nigeria?', a: `About ${range('duplex-4', 'basic')} with basic finishes, ${range('duplex-4')} with standard finishes and ${range('duplex-4', 'premium')} with premium finishes in Lagos in 2026, excluding land.` },
        { q: 'How much does it cost to build a 5-bedroom duplex in Nigeria?', a: `About ${range('duplex-5', 'basic')} basic, ${range('duplex-5')} standard and ${range('duplex-5', 'premium')} premium, excluding land.` },
        { q: 'How long does it take to build a duplex?', a: 'Usually 12–24 months from building approval to handover. Funding in steady stages is the biggest factor.' },
        { q: 'Can I build a duplex in stages as money comes in?', a: 'Yes. Many clients fund foundation to roof first, then finishing. We plan stage payments so each stage leaves the building protected (for example, roofing before a long pause).' },
        { q: 'Does the cost include the boys’ quarters (BQ) and fence?', a: 'No. A BQ is priced like a small bungalow by floor area; fence, gate, paving and borehole are external works, usually 10–20% extra.' },
    ],
    sources: SOURCES,
    related: related('/guides/cost-of-building-a-duplex-in-nigeria'),
    cta: COST_CTA,
}

export const bungalowGuide = {
    kind: 'guide',
    path: '/guides/cost-of-building-a-bungalow-in-nigeria',
    title: 'Cost of Building a 3-Bedroom Bungalow in Nigeria (2026)',
    description: `A 3-bedroom bungalow in Lagos costs about ${fmtM(estimate('bungalow-3', 'basic')[0])} to ${fmtM(estimate('bungalow-3', 'premium')[1])} to build in 2026, excluding land. 2-, 3- and 4-bedroom costs in ₦, £ and $.`,
    breadcrumbs: [{ name: 'Guides', path: '/guides' }, { name: 'Cost of building a bungalow', path: '/guides/cost-of-building-a-bungalow-in-nigeria' }],
    eyebrow: 'Cost guide · Bungalow · 2026',
    h1: 'Cost of building a 3-bedroom bungalow in Nigeria (2026)',
    intro: `A **3-bedroom bungalow** in Lagos costs about **${range('bungalow-3')}** to build with standard finishes in 2026, and a **4-bedroom bungalow** about **${range('bungalow-4')}**, excluding land. A simple 2-bedroom bungalow can start from around **${fmtM(estimate('bungalow-2', 'basic')[0])}**.`,
    updated: COSTS_VERIFIED,
    published: '2026-10-02',
    hero: '/100.jpeg',
    heroAlt: 'Completed home with paved courtyard',
    currency: true,
    whatsappText: 'Hi Artemis, I read your bungalow cost guide and would like an estimate.',
    summary: [
        `2-bedroom (~90 m²): ${range('bungalow-2', 'basic')} basic · ${range('bungalow-2')} standard.`,
        `3-bedroom (~130 m²): ${range('bungalow-3', 'basic')} basic · ${range('bungalow-3')} standard · ${range('bungalow-3', 'premium')} premium.`,
        `4-bedroom (~170 m²): ${range('bungalow-4', 'basic')} basic · ${range('bungalow-4')} standard · ${range('bungalow-4', 'premium')} premium.`,
        'Timeline: usually 6–12 months from approval to handover.',
    ],
    blocks: [
        { t: 'h2', text: 'Bungalow costs at a glance' },
        { t: 'table', caption: 'Bungalow building cost, Lagos 2026', head: ['Bungalow', 'Basic', 'Standard', 'Premium'], rows: typeRows(['bungalow-2', 'bungalow-3', 'bungalow-4']), note: 'Building only, excluding land, approvals and external works. Rounded to ₦0.5m.' },
        { t: 'h2', text: '3-bedroom bungalow: cost stage by stage' },
        { t: 'table', caption: '3-bedroom bungalow cost by stage (standard finish)', head: ['Stage', 'Share', 'Approx. cost', 'What it covers'], rows: stageRows('bungalow-3') },
        { t: 'h2', text: '4-bedroom bungalow: cost stage by stage' },
        { t: 'table', caption: '4-bedroom bungalow cost by stage (standard finish)', head: ['Stage', 'Share', 'Approx. cost', 'What it covers'], rows: stageRows('bungalow-4') },
        { t: 'h2', text: 'Bungalow or duplex?' },
        { t: 'table', caption: 'Bungalow vs duplex', head: ['', 'Bungalow', 'Duplex'], rows: [
            ['Cost per m²', 'Lower: no suspended slab or stairs', 'Higher: first-floor slab, stairs, heavier frame'],
            ['Land needed', 'More: everything on one floor', 'Less: about half the footprint for the same rooms'],
            ['Build time', '6–12 months', '12–24 months'],
            ['Best for', 'Larger or cheaper plots, ageing parents, adding floors later', 'Small or expensive plots, privacy between living and sleeping areas'],
        ] },
        { t: 'callout', text: 'Planning to add a floor later? Tell us at design stage. We size the foundation and columns for a future upper floor, which costs far less than strengthening later.' },
        { t: 'h2', text: 'Current material prices' },
        { t: 'prices', compact: true },
    ],
    faqs: [
        { q: 'How much does it cost to build a 3-bedroom bungalow in Nigeria?', a: `About ${range('bungalow-3', 'basic')} with basic finishes and ${range('bungalow-3')} with standard finishes in Lagos in 2026, excluding land.` },
        { q: 'How much does it cost to build a 4-bedroom bungalow in Nigeria?', a: `About ${range('bungalow-4', 'basic')} basic, ${range('bungalow-4')} standard and ${range('bungalow-4', 'premium')} premium, excluding land.` },
        { q: 'How much does it cost to build a 2-bedroom bungalow?', a: `About ${range('bungalow-2', 'basic')} with basic finishes and ${range('bungalow-2')} with standard finishes.` },
        { q: 'Can I build a bungalow with ₦20 million?', a: 'A small 2-bedroom bungalow with basic finishes is possible around that figure on normal soil, outside premium areas, if land is already paid for. A 3-bedroom bungalow usually needs more.' },
        { q: 'How long does it take to build a bungalow?', a: 'Usually 6–12 months from approval to handover.' },
    ],
    sources: SOURCES,
    related: related('/guides/cost-of-building-a-bungalow-in-nigeria'),
    cta: COST_CTA,
}

export const housePriceGuide = {
    kind: 'guide',
    path: '/guides/how-much-is-a-house-in-nigeria',
    title: 'How Much Is a House in Nigeria? 2026 Prices in ₦, £ and $',
    description: 'House prices in Lagos in 2026 by area, in naira, pounds and dollars, and when building costs less than buying. From Ikorodu and Epe to Lekki and Ikoyi.',
    breadcrumbs: [{ name: 'Guides', path: '/guides' }, { name: 'How much is a house in Nigeria?', path: '/guides/how-much-is-a-house-in-nigeria' }],
    eyebrow: 'Guide · Buy or build · 2026',
    h1: 'How much is a house in Nigeria in 2026?',
    intro: 'A house in Lagos costs anything from about **₦45m for a 3-bedroom flat on the mainland** to **over ₦1bn for a duplex in Ikoyi**. A 4-bedroom duplex in Ajah typically lists for **₦95m–₦160m**. Building your own is often cheaper per square metre, and you control the quality.',
    updated: '2026-10-02',
    published: '2026-10-02',
    hero: '/101-hero.jpeg',
    heroAlt: 'Completed residence with gate and boundary wall',
    currency: true,
    whatsappText: 'Hi Artemis, I am deciding whether to buy or build in Lagos.',
    summary: [
        'Mainland 3-bedroom flat (e.g. Yaba): about ₦45m–₦85m.',
        'Lekki Phase 1 3-bedroom flat: about ₦120m–₦250m.',
        '4-bedroom duplex in Ajah: about ₦95m–₦160m; in Ikoyi or Victoria Island: ₦450m–₦1.2bn.',
        `Building a 4-bedroom duplex costs about ${range('duplex-4')} plus land.`,
    ],
    blocks: [
        { t: 'h2', text: 'House prices in Lagos by area' },
        { t: 'p', text: 'Typical asking prices from listings in early 2026. Use the currency switch to see pounds or dollars at today’s rate.' },
        { t: 'table', caption: 'Lagos house prices by area, 2026', head: ['Area and property', 'Typical asking price'], rows: [
            ['Yaba (mainland) — 3-bedroom flat', { ngn: [45e6, 85e6] }],
            ['Lekki Phase 1 — 3-bedroom flat', { ngn: [120e6, 250e6] }],
            ['Ajah — 4-bedroom duplex', { ngn: [95e6, 160e6] }],
            ['Surulere — 4-bedroom duplex', { ngn: 240e6, plus: false }],
            ['Gbagada — 4-bedroom duplex', { ngn: 250e6 }],
            ['Ikeja GRA — 4-bedroom duplex', { ngn: 500e6 }],
            ['Ikoyi / Victoria Island — 4-bedroom duplex', { ngn: [450e6, 1.2e9] }],
        ], note: 'Source: Nigeria Housing Market, Lagos property prices (January 2026). Single figures are typical prices. Asking prices are not sale prices.' },
        { t: 'h2', text: 'Land prices: the other half of the decision' },
        { t: 'table', caption: 'Lagos land prices per plot, 2026', head: ['Area', 'Typical price per plot (about 600 m²)'], rows: [
            ['Ikorodu', { ngn: 15e6 }],
            ['Epe', { ngn: 27e6 }],
            ['Ajah / VGC', { ngn: 210e6 }],
            ['Lekki Phase 1', { ngn: 570e6 }],
            ['Ikoyi', { ngn: 1.08e9, plus: true }],
        ], note: 'Source: Nigeria Housing Market (January 2026). Prices vary widely by estate and title.' },
        { t: 'h2', text: 'Buy or build?' },
        { t: 'table', caption: 'Buying vs building in Lagos', head: ['', 'Buy a finished house', 'Build your own'], rows: [
            ['Price', 'Includes the developer’s margin', `Building cost only (e.g. ${range('duplex-4')} for a 4-bed duplex) plus land`],
            ['Quality', 'Hard to see what is inside walls and foundations', 'You choose materials; each stage is inspected'],
            ['Time to move in', 'Weeks to months', '12–24 months for a duplex'],
            ['Title risk', 'Check the title of the house and the estate', 'Check the land title before you buy it'],
            ['Design', 'As built', 'Designed for your family and plot'],
        ] },
        { t: 'p', text: 'Building usually wins when you already own land, want a particular design, or are buying in a growing area (Ibeju-Lekki, Epe, Ikorodu) where finished stock is limited. Buying wins when you need to move in soon. Whichever you choose, verify the title first: see [buying land in Nigeria from abroad](/guides/buying-land-in-nigeria-from-abroad).' },
        { t: 'h2', text: 'How much is a house in Nigeria in US dollars or pounds?' },
        { t: 'p', text: 'Switch the currency at the top of this page to convert every figure. As a rule of thumb at October 2026 official rates, ₦100m is about $75,000 or £57,000.' },
    ],
    faqs: [
        { q: 'How much is a house in Nigeria in US dollars?', a: 'At October 2026 official rates (about ₦1,329 to $1), a mainland 3-bedroom flat at ₦45m–₦85m is roughly $34,000–$64,000, and a 4-bedroom duplex in Ajah at ₦95m–₦160m is roughly $71,000–$120,000.' },
        { q: 'What is the average house price in Lagos?', a: 'There is no reliable official average. Listings run from about ₦45m for mainland flats to over ₦1bn in Ikoyi; most family homes in growing areas like Ajah list between ₦95m and ₦160m.' },
        { q: 'Is it cheaper to build a house in Nigeria than to buy one?', a: `Usually, if you already have land: a 4-bedroom duplex costs about ${range('duplex-4')} to build with standard finishes. Buying saves time but includes a developer margin.` },
        { q: 'Can foreigners or Nigerians abroad buy property in Nigeria?', a: 'Nigerians abroad can buy and hold land like any Nigerian. Foreign nationals face restrictions under the Land Use Act and usually hold property through a lease or company; take legal advice.' },
    ],
    sources: [
        { name: 'Nigeria Housing Market — Lagos property prices 2026', url: 'https://www.nigeriahousingmarket.com/lagos/property-prices', date: 'January 2026' },
        { name: 'CBN official exchange rates', url: 'https://www.cbn.gov.ng/rates/ExchRateByCurrency.html', date: 'October 2026' },
        ...SOURCES.slice(0, 2),
    ],
    related: related('/guides/how-much-is-a-house-in-nigeria'),
    cta: { ...COST_CTA, title: 'Compare buying with building on your plot', label: 'Book a consultation' },
}
