// Service pages (/services/*) and the Lagos contractor page.
import { ADVISORY } from './services-advisory'

const SERVICES_RELATED = [
    { label: 'Design and build', href: '/services/design-and-build', text: 'One team from drawings to keys.' },
    { label: 'Renovation and interior finishing', href: '/services/renovation-and-interior-finishing', text: 'Remodelling, fit-outs, kitchens and finishes.' },
    { label: 'Facility management and commercial', href: '/services/facility-management-and-commercial', text: 'Maintenance, office fit-outs and commercial builds.' },
    { label: 'How we build', href: '/how-we-build', text: 'Stage payments, inspections and reporting.' },
    { label: 'Our projects', href: '/portfolio', text: 'Homes, estates, churches and commercial work.' },
    { label: 'Cost of building a house', href: '/guides/cost-of-building-a-house-in-nigeria', text: '2026 costs in naira, pounds and dollars.' },
]
const related = self => SERVICES_RELATED.filter(r => r.href !== self)

const CORE_SERVICES = [
    {
        kind: 'service',
        slug: 'design-and-build',
        path: '/services/design-and-build',
        card: { h: 'Design and build', p: 'Architecture, structural design, approvals and construction by one accountable team.' },
        title: 'Design and Build Company in Lagos | Artemis Atelier',
        description: 'Design and build in Lagos: architectural design, structural engineering, permits and construction by one team, with open-book BOQs and inspected stages.',
        serviceName: 'Design and build',
        serviceType: 'Design and build construction',
        breadcrumbs: [{ name: 'Services', path: '/services' }, { name: 'Design and build', path: '/services/design-and-build' }],
        eyebrow: 'Service · Design and build',
        h1: 'Design and build in Lagos, from first sketch to keys',
        intro: 'With design and build, **one firm is responsible for the drawings and the building**. Our architects and COREN-registered engineers design your house, estate, church or office, get it approved, price it in an open-book bill of quantities, and build it in inspected stages.',
        updated: '2026-10-02',
        hero: '/31.jpg',
        heroAlt: 'Design visual of a residential development at Arepo',
        whatsappText: 'Hi Artemis, I would like to start a design brief.',
        blocks: [
            { t: 'h2', text: 'What is included' },
            { t: 'cards', items: [
                { h: 'Architectural design', p: 'Brief, concept options, 3D visuals and approval-ready drawings designed for your plot and budget.' },
                { h: 'Structural and services design', p: 'Foundation, frame and roof design by registered engineers; electrical and plumbing layouts.' },
                { h: 'Approvals', p: 'Planning permit applications and the inspections that follow.' },
                { h: 'Costing', p: 'An itemised, open-book BOQ before construction, so the budget is fixed against the design.' },
                { h: 'Construction', p: 'Our site team builds to the drawings, with an inspection at every stage before the next payment.' },
                { h: 'Handover', p: 'As-built drawings, warranties and a defects liability period after you move in.' },
            ] },
            { t: 'h2', text: 'Why design and build' },
            { t: 'ul', items: [
                '**One point of responsibility.** No gap between an architect who drew it and a builder who says it can’t be built.',
                '**Cost control from day one.** We design to your budget and price as we draw.',
                '**Faster.** Design, approvals and procurement overlap instead of running one after another.',
            ] },
            { t: 'h2', text: 'What we design' },
            { t: 'ul', items: [
                'Family homes: bungalows, duplexes, terraces and homes with BQ. See our [house plans and designs](/house-plans).',
                'Estates and multi-unit residential developments.',
                'Churches and community buildings.',
                'Offices and commercial buildings.',
            ] },
            { t: 'h2', text: 'How it works' },
            { t: 'steps', items: [
                { h: 'Free consultation', p: 'Your plot, budget, timeline and how you want to live or work.' },
                { h: 'Design brief and concept', p: 'Options and visuals; you choose a direction.' },
                { h: 'Drawings, approvals and BOQ', p: 'Full drawings, permit application and an open-book cost.' },
                { h: 'Build in inspected stages', p: 'You pay stage by stage after each is checked. See [how we build](/how-we-build).' },
                { h: 'Handover', p: 'Keys, documents and the defects liability period.' },
            ] },
        ],
        faqs: [
            { q: 'What is a design and build company?', a: 'A firm that both designs and constructs your building under one contract, so one party is responsible for the drawings, the cost and the construction.' },
            { q: 'How much does architectural design cost in Lagos?', a: 'Design fees depend on the size and complexity of the building. On a design-and-build project we include them in your project budget and show them as a line in the BOQ.' },
            { q: 'Can you design for a plot I haven’t bought yet?', a: 'Yes. We can test what fits on a plot before you buy, which often changes which plot you choose. See [buying land from abroad](/guides/buying-land-in-nigeria-from-abroad).' },
        ],
        related: related('/services/design-and-build'),
        cta: { title: 'Start a design brief', text: 'Tell us about your plot and what you want to build.', label: 'Start a design brief', href: '/contact#enquiry' },
        consult: { title: 'Start a design brief', text: 'A free call to talk through your plot, budget and ideas.', primary: { label: 'Book a call', href: '/build-from-abroad#book' } },
    },
    {
        kind: 'service',
        slug: 'renovation-and-interior-finishing',
        path: '/services/renovation-and-interior-finishing',
        card: { h: 'Renovation and interior finishing', p: 'Remodelling, extensions, fit-outs, kitchens, wardrobes and finishes for homes and offices.' },
        title: 'House Renovation & Interior Finishing in Lagos | Artemis',
        description: 'House renovation and interior finishing in Lagos: extensions, kitchens, tiling, POP and paint, priced in an open-book BOQ and managed for clients abroad.',
        serviceName: 'Renovation and interior finishing',
        serviceType: 'House renovation',
        breadcrumbs: [{ name: 'Services', path: '/services' }, { name: 'Renovation and interior finishing', path: '/services/renovation-and-interior-finishing' }],
        eyebrow: 'Service · Renovation',
        h1: 'House renovation and interior finishing in Lagos',
        intro: 'We renovate and finish homes and offices across Lagos: **structural remodelling, extensions, re-roofing, kitchens, wardrobes, tiling, ceilings and paint**. Every job starts with a survey of what is really there, is priced line by line, and is reported with photos, so you can renovate a family house from abroad.',
        updated: '2026-10-02',
        hero: '/100.jpeg',
        heroAlt: 'Completed home with paved courtyard',
        whatsappText: 'Hi Artemis, I would like a renovation quote.',
        blocks: [
            { t: 'h2', text: 'Renovation work we do' },
            { t: 'cards', items: [
                { h: 'Remodelling and extensions', p: 'Removing or moving walls safely, adding rooms or a floor, after a structural check.' },
                { h: 'Roof and waterproofing', p: 'Re-roofing, leak repairs, gutters and damp treatment.' },
                { h: 'Kitchens and wardrobes', p: 'Fitted kitchens, wardrobes and storage, designed and installed.' },
                { h: 'Interior finishing', p: 'Tiling, POP and suspended ceilings, screeding, painting, doors and windows.' },
                { h: 'Services upgrades', p: 'Rewiring, plumbing, bathrooms, solar and inverter-ready wiring.' },
                { h: 'Completing unfinished buildings', p: 'Taking over a stalled project: survey, BOQ for what is left, and finishing it.' },
            ] },
            { t: 'h2', text: 'How a renovation works' },
            { t: 'steps', items: [
                { h: 'Survey', p: 'We inspect the building, test what we need to, and photograph everything.' },
                { h: 'Scope and BOQ', p: 'A written scope and itemised price; you choose finishes from samples.' },
                { h: 'Work in stages', p: 'Paid per completed stage, with photo reports if you are abroad.' },
                { h: 'Snagging and handover', p: 'We fix the snag list before final payment.' },
            ] },
            { t: 'callout', text: 'Taking over an abandoned or half-finished build? We start with a structural check of the existing work: it is cheaper to find problems before you build on them.' },
        ],
        faqs: [
            { q: 'How much does house renovation cost in Lagos?', a: 'It depends entirely on scope. Finishing works alone typically make up 30–40% of a new build’s cost; we price each renovation from a survey in an itemised BOQ.' },
            { q: 'Can you renovate my parents’ house while I am abroad?', a: 'Yes. We survey, agree scope and finishes with you on video calls, and send photo reports at each stage before payment.' },
            { q: 'Do you finish buildings another contractor abandoned?', a: 'Yes, after a structural check of the existing work and a BOQ for what remains.' },
        ],
        related: related('/services/renovation-and-interior-finishing'),
        cta: { title: 'Get a renovation quote', text: 'Send photos and a short description; we’ll arrange a survey.', label: 'Get a renovation quote', href: '/contact#enquiry' },
        consult: { title: 'Get a renovation quote', text: 'Send us photos on WhatsApp or book a survey.', primary: { label: 'Request a survey', href: '/contact#enquiry' } },
    },
    {
        kind: 'service',
        slug: 'facility-management-and-commercial',
        path: '/services/facility-management-and-commercial',
        card: { h: 'Facility management and commercial', p: 'Planned maintenance, office fit-outs and commercial and institutional buildings.' },
        title: 'Facility Management Companies in Nigeria | Artemis Atelier',
        description: 'Facility management services in Nigeria and commercial construction in Lagos: planned maintenance, repairs, office fit-outs and new commercial buildings.',
        serviceName: 'Facility management and commercial construction',
        serviceType: 'Facility management',
        breadcrumbs: [{ name: 'Services', path: '/services' }, { name: 'Facility management and commercial', path: '/services/facility-management-and-commercial' }],
        eyebrow: 'Service · For organisations',
        h1: 'Facility management in Nigeria and commercial construction',
        intro: 'For companies, churches, schools and property owners, we **look after buildings** (planned maintenance, repairs and upgrades) and **build and fit out commercial space**, from office fit-outs in Lagos to new institutional buildings, with the same open-book costing and reporting as our homes.',
        updated: '2026-10-02',
        hero: '/36.jpg',
        heroAlt: 'Design visual of a church complex at Epe',
        whatsappText: 'Hi Artemis, I would like a corporate proposal.',
        blocks: [
            { t: 'h2', text: 'Facility management services' },
            { t: 'cards', items: [
                { h: 'Planned preventive maintenance', p: 'Scheduled checks of roofs, drainage, electrical, plumbing and structure, with reports.' },
                { h: 'Reactive repairs', p: 'A single point of contact for faults, with agreed response times.' },
                { h: 'Condition surveys', p: 'A survey of your building’s state and a prioritised, costed repair plan.' },
                { h: 'Upgrades and refurbishment', p: 'Energy, safety and accessibility upgrades without closing the building.' },
            ] },
            { t: 'h2', text: 'Commercial construction and fit-outs' },
            { t: 'ul', items: [
                'Office fit-outs in Lagos: partitions, ceilings, flooring, lighting, data and power.',
                'Retail and hospitality interiors.',
                'New commercial and institutional buildings, including churches and community buildings.',
                'Project management of multi-contractor works.',
            ] },
            { t: 'h2', text: 'How we work with organisations' },
            { t: 'steps', items: [
                { h: 'Site survey and brief', p: 'We review your buildings, documents and priorities.' },
                { h: 'Proposal', p: 'Scope, service levels, programme and an itemised price.' },
                { h: 'Delivery and reporting', p: 'Work orders, photo reports and monthly summaries for your board or finance team.' },
            ] },
        ],
        faqs: [
            { q: 'What does a facility management company do?', a: 'It keeps buildings safe and working: planned maintenance, repairs, condition surveys and upgrades, usually under a service agreement with agreed response times and reporting.' },
            { q: 'Do you do office fit-outs in Lagos?', a: 'Yes: partitions, ceilings, flooring, lighting, power and data, priced in an itemised BOQ.' },
            { q: 'Can you manage maintenance for a property I own but don’t live in?', a: 'Yes. We inspect on a schedule and send reports and photos, which suits owners abroad.' },
        ],
        related: related('/services/facility-management-and-commercial'),
        cta: { title: 'Request a corporate proposal', text: 'Tell us about your buildings and what you need.', label: 'Request a proposal', href: '/contact#enquiry' },
        consult: { title: 'Request a corporate proposal', text: 'A call to understand your buildings and priorities.', primary: { label: 'Contact us', href: '/contact#enquiry' } },
    },
]

// Build services first, then the advisory services (lib/content/services-advisory.js)
export const SERVICES = [...CORE_SERVICES, ...ADVISORY]

export const contractorLagos = {
    kind: 'service',
    path: '/building-contractor-lagos',
    title: 'Building Contractor in Lagos | Artemis Atelier (RC 1484495)',
    description: 'Lagos building contractor since 2010: homes, duplexes, estates and churches, with COREN engineers, open-book BOQs, live site cameras and inspected stages.',
    serviceName: 'Building contractor in Lagos',
    serviceType: 'General contractor',
    areaServed: ['Lagos', 'Ogun State'],
    breadcrumbs: [{ name: 'Building contractor in Lagos', path: '/building-contractor-lagos' }],
    eyebrow: 'Lagos building contractor since 2010',
    h1: 'A building contractor in Lagos you can check, not just trust',
    intro: 'Artemis Atelier Ltd is a **registered Lagos building contractor (RC 1484495)** working from Anthony Village since 2010. We build **houses, duplexes, estates, churches and commercial buildings** across Lagos and nearby Ogun State, with COREN-registered engineers, an itemised BOQ, a live site camera and payments released only after each stage is inspected.',
    updated: '2026-10-02',
    hero: '/26.jpg',
    heroAlt: 'Residential development at Atican Beach View Estate',
    whatsappText: 'Hi Artemis, I am looking for a building contractor in Lagos.',
    blocks: [
        { t: 'h2', text: 'What we build' },
        { t: 'cards', items: [
            { h: 'Homes', p: 'Bungalows, duplexes, terraces and homes with BQ — for owners in Lagos and abroad.', href: '/services/design-and-build', cta: 'Design and build' },
            { h: 'Estates', p: 'Multi-unit residential developments, from design to handover.', href: '/portfolio', cta: 'See projects' },
            { h: 'Churches and community buildings', p: 'Including the proposed Catholic church complex at Epe.', href: '/portfolio/epe-catholic-church-complex', cta: 'See the project' },
            { h: 'Renovation and commercial', p: 'Remodelling, finishing, fit-outs and maintenance.', href: '/services/renovation-and-interior-finishing', cta: 'Renovation' },
        ] },
        { t: 'h2', text: 'Where we work' },
        { t: 'p', text: 'Across Lagos (Island and mainland: Ikoyi, Lekki, Ajah, Epe, Ikeja, Anthony Village and beyond) and nearby Ogun State, including Arepo and OPIC. Ask us about other locations.' },
        { t: 'h2', text: 'How we protect your money' },
        { t: 'infographic', name: 'protection', title: 'Five layers that protect your money' },
        { t: 'checklist', items: [
            '**Stage payments:** you pay for one stage at a time — foundation, frame, roof, finishing.',
            '**Stage inspection** by our named inspection team before each payment is released (you can add an independent inspector).',
            '**Open-book BOQ:** every bag of cement and tonne of rebar itemised.',
            '**Live site camera** and weekly photo reports.',
            '**Insurance**: contractor’s all-risk cover can be arranged with a NAICOM-licensed insurer, subject to the policy terms.',
            '**6–12 month defects liability period** and a full handover pack.',
        ] },
        { t: 'p', text: 'Read the full process: [how we build](/how-we-build).' },
        { t: 'h2', text: 'Choosing between contractors?' },
        { t: 'p', text: 'Use our free [contractor checklist](/guides/how-to-choose-a-building-contractor-in-nigeria) and [guide to construction companies in Lagos](/guides/construction-companies-in-lagos). We are happy to be compared on every point.' },
    ],
    faqs: [
        { q: 'How do I find a good building contractor in Lagos?', a: 'Check CAC registration, COREN engineers and ARCON architect, see finished projects, compare itemised BOQs, and insist on stage payments after independent inspection.' },
        { q: 'Which areas of Lagos do you work in?', a: 'All of Lagos, Island and mainland, and nearby Ogun State. Ask us about other locations.' },
        { q: 'Do you offer a free site consultation?', a: 'Yes: a free 20-minute consultation by phone, video call or WhatsApp, then a site assessment if you go ahead.' },
        { q: 'Are you registered?', a: 'Yes. Artemis Atelier Ltd is registered with the Corporate Affairs Commission, RC 1484495, and our structural work is led by a COREN-registered engineer.' },
    ],
    related: [
        { label: 'Our projects', href: '/portfolio', text: 'Homes, estates, churches and commercial work.' },
        { label: 'How we build', href: '/how-we-build', text: 'Stage payments, inspections and reporting.' },
        { label: 'Cost of building a house', href: '/guides/cost-of-building-a-house-in-nigeria', text: '2026 costs in naira, pounds and dollars.' },
        { label: 'Construction companies in Lagos', href: '/guides/construction-companies-in-lagos', text: 'How to compare them.' },
        { label: 'Build from abroad', href: '/build-from-abroad', text: 'For clients in the UK, US, Canada and beyond.' },
        { label: 'Who we are', href: '/people', text: 'The architects, engineers and managers behind every project.' },
    ],
    cta: { title: 'Book a site consultation', text: 'Free 20-minute call, then a visit to your plot.', label: 'Book a site consultation', href: '/contact#book', secondary: { label: 'See our projects', href: '/portfolio' } },
    consult: { title: 'Book a site consultation', text: 'Free 20-minute call about your plot, budget and timeline.', primary: { label: 'Book a call', href: '/contact#book' } },
}
